/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/session/create": {
    /** 创建新的聊天会话 */
    post: operations["createChatSession"];
  };
  "/session/list": {
    /** 获取历史会话列表，游标分页 */
    get: operations["listChatSessions"];
  };
  "/ai/chat": {
    /**
     * 聊天接口
     * @description 与AI进行对话，返回AI生成的回复
     */
    get: operations["chat"];
  };
  "/session/delete": {
    /** 删除聊天会话 */
    delete: operations["deleteChatSession"];
  };
  "/session/batch-delete": {
    /** 批量删除聊天会话 */
    delete: operations["batchDeleteChatSessions"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ResultString: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: string;
    };
    ChatSessionVO: {
      conversationId?: string;
      userId?: string;
      title?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      lastMessage?: string;
    };
    ResultListChatSessionVO: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: components["schemas"]["ChatSessionVO"][];
    };
    ResultBoolean: {
      /** Format: int32 */
      code?: number;
      message?: string;
      data?: boolean;
    };
    ResultInteger: {
      /** Format: int32 */
      code?: number;
      message?: string;
      /** Format: int32 */
      data?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** 创建新的聊天会话 */
  createChatSession: {
    parameters: {
      query: {
        /** @description 用户ID */
        userId: string;
        /** @description 会话标题 */
        title?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultString"];
        };
      };
    };
  };
  /** 获取历史会话列表，游标分页 */
  listChatSessions: {
    parameters: {
      query: {
        /** @description 用户ID */
        userId: string;
        /** @description 最后一次查询到的会话Id */
        lastConversationId?: string;
        /** @description 单页大小 */
        pageSize?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultListChatSessionVO"];
        };
      };
    };
  };
  /**
   * 聊天接口
   * @description 与AI进行对话，返回AI生成的回复
   */
  chat: {
    parameters: {
      query: {
        /** @description 用户输入的提示词 */
        prompt: string;
        /** @description 会话Id */
        chatId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "text/event-stream;charset=UTF-8": string[];
        };
      };
    };
  };
  /** 删除聊天会话 */
  deleteChatSession: {
    parameters: {
      query: {
        /** @description 用户ID */
        userId: string;
        /** @description 会话ID */
        conversationId: string;
        /** @description 是否清理聊天记录 */
        clearChatMemory?: boolean;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultBoolean"];
        };
      };
    };
  };
  /** 批量删除聊天会话 */
  batchDeleteChatSessions: {
    parameters: {
      query: {
        /** @description 用户ID */
        userId: string;
        /** @description 是否清理聊天记录 */
        clearChatMemory?: boolean;
      };
    };
    requestBody: {
      content: {
        "application/json": string[];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ResultInteger"];
        };
      };
    };
  };
}
